#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/branches/git/fp-freshports \
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/fp-freshports-${VERSION} -m "'${MSG}'"

cd ~/tmp
svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/fp-freshports-${VERSION} freshports-fp-freshports-${VERSION}

tar -czf freshports-fp-freshports-${VERSION}.tar.gz freshports-fp-freshports-${VERSION}
scp freshports-fp-freshports-${VERSION}.tar.gz pkg01:
rm -rf freshports-fp-freshports-${VERSION}
