#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/scripts/trunk \
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/scripts/tags/${VERSION} -m "'${MSG}'"

cd ~/tmp
rm -rf FreshPorts-Scripts-${VERSION}

svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/scripts/tags/${VERSION} FreshPorts-Scripts-${VERSION}

tar -czf FreshPorts-Scripts-${VERSION}.tar.gz FreshPorts-Scripts-${VERSION}
scp FreshPorts-Scripts-${VERSION}.tar.gz r710-01:
