#!/bin/sh

VERSION=$1
MSG=$2

echo svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshsource/www/branches/git \
         svn+ssh://svnusers@svn.int.unixathome.org/freshsource/www/tags/freshsource-${VERSION} -m "'${MSG}'"
svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshsource/www/branches/git \
         svn+ssh://svnusers@svn.int.unixathome.org/freshsource/www/tags/freshsource-${VERSION} -m "'${MSG}'"
         
cd ~/tmp
svn export svn+ssh://svnusers@svn.int.unixathome.org/freshsource/www/tags/freshsource-${VERSION} freshsource-${VERSION}

tar -czf freshsource-${VERSION}.tar.gz freshsource-${VERSION}
scp freshsource-${VERSION}.tar.gz pkg01.int.unixathome.org:
