#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/modules/trunk \
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/modules/tags/${VERSION} -m "'${MSG}'"

cd ~/tmp
rm -rf FreshPorts-Modules-${VERSION}

svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/ingress/modules/tags/${VERSION} FreshPorts-Modules-${VERSION}

cd FreshPorts-Modules-${VERSION}

chmod -x xml_munge.pm status.pm.sample process_svn_mail.pm process_cvs_mail.pm commit_log_ports_ignore.pm

cd -

tar -czf FreshPorts-Modules-${VERSION}.tar.gz FreshPorts-Modules-${VERSION}
scp FreshPorts-Modules-${VERSION}.tar.gz r710-01:
