#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/branches/git/ingress_svn\
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/ingress_svn-${VERSION} -m "'${MSG}'"

cd ~/tmp
svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/ingress_svn-${VERSION} freshports-ingress-svn-${VERSION}

tar -czf freshports-ingress-svn-${VERSION}.tar.gz freshports-ingress-svn-${VERSION}
scp freshports-ingress-svn-${VERSION}.tar.gz pkg01.int.unixathome.org:
