#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freebsddiary/trunk \
         svn+ssh://svnusers@svn.int.unixathome.org/freebsddiary/tags/${VERSION} -m "'${MSG}'"

cd ~/tmp
svn export svn+ssh://svnusers@svn.int.unixathome.org/freebsddiary/tags/${VERSION} freebsddiary-${VERSION}

tar -czf freebsddiary-${VERSION}.tar.gz freebsddiary-${VERSION}
scp freebsddiary-${VERSION}.tar.gz r720-01:
