#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/trunk \
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/freshports-services-${VERSION} -m "'${MSG}'"

cd ~/tmp
svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/freshports-services-${VERSION} freshports-services-${VERSION}

tar -czf freshports-fp-listen-${VERSION}.tar.gz freshports-fp-listen-${VERSION}
scp freshports-fp-listen-${VERSION}.tar.gz r710-01:
