#!/bin/sh

VERSION=$1
MSG=$2

svn copy svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/branches/git/ingress \
         svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/ingress-${VERSION} -m "'${MSG}'"

cd ~/tmp/packaging/
svn export svn+ssh://svnusers@svn.int.unixathome.org/freshports-1/daemontools/tags/ingress-${VERSION} freshports-ingress-${VERSION}

tar -czf freshports-ingress-${VERSION}.tar.gz freshports-ingress-${VERSION}
scp freshports-ingress-${VERSION}.tar.gz pkg01:
rm -rf freshports-ingress-${VERSION}
